- name: Check if app exists
  ansible.builtin.set_fact:
    app_exists: "{{ existing_apps | json_query(app_query) | length() > 0 }}"
    found_apps: "{{ existing_apps | json_query(app_query) }}"
  vars:
    app_query: "[?name == `{{ app.name }}`]"

- name: Create app
  ansible.builtin.uri:
    url: "https://{{ flame_name }}.{{ domain }}/api/apps"
    method: POST
    body_format: json
    body:
      name: "{{ app.name }}"
      url: "{{ app.url }}"
      icon: "{{ app.icon }}"
    status_code: 201
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  when: not app_exists

- name: Update existing app
  ansible.builtin.uri:
    url: "https://{{ flame_name }}.{{ domain }}/api/apps/{{ i.id }}"
    method: PUT
    body_format: json
    body:
      name: "{{ app.name }}"
      url: "{{ app.url }}"
      icon: "{{ app.icon }}"
    status_code: 200
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  when: app_exists and (i.name != app.name or i.url != app.url or i.icon != app.icon)
  with_items: "{{ found_apps }}"
  loop_control:
    loop_var: i