- name: Get flame apps
  ansible.builtin.uri:
    url: "https://{{ domain }}/api/apps"
    method: GET
    status_code: 200
    validate_certs: "{{ validate_certificates }}"
    headers:
      Authorization: "Bearer {{ flame_token }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404

- name: Save flame app ids
  ansible.builtin.set_fact:
    present_flame_apps: "{{ _response.json.data }}"

- name: Remove flame app
  ansible.builtin.uri:
    url: "https://{{ domain }}/api/apps/{{ item.id }}"
    method: DELETE
    status_code: 200
    validate_certs: "{{ validate_certificates }}"
    headers:
      Authorization: "Bearer {{ flame_token }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  with_items: "{{ present_flame_apps }}"