global:
  scrape_interval: 30s
  external_labels:
    monitor: coresvc

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node-exporter
    static_configs:
      - targets: ['192.168.1.2:9100', '192.168.1.4:9100']

